//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.13 at 06:28:53 PM YEKT 
//


package com.github.tr1cks.xjcplugins;

import java.io.Serializable;
import java.math.BigDecimal;
import java.math.BigInteger;
import javax.annotation.Nullable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="from" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="to" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="body" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="anonymousByteElemByDigits">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *               &lt;totalDigits value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="byteElemByDigits" type="{com.github.trickster88.xjcplugins}byteByDigits"/>
 *       &lt;/sequence>
 *       &lt;attribute name="floatNum" use="required" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="doubleNum" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="decimalNum" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="byteNumByDigits">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *             &lt;totalDigits value="2"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="shortNumByDigits" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *             &lt;totalDigits value="4"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="intNumByDigits">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *             &lt;totalDigits value="9"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="longNumByDigits" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *             &lt;totalDigits value="18"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="bigIntegerNumByDigits">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *             &lt;totalDigits value="19"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="byteNumByZeroInclusiveRange" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *             &lt;minInclusive value="0"/>
 *             &lt;maxInclusive value="0"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="byteNumByZeroExclusiveRange">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *             &lt;minExclusive value="-1"/>
 *             &lt;maxExclusive value="1"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="byteNumByInclusiveRange">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *             &lt;minInclusive value="-128"/>
 *             &lt;maxInclusive value="127"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="byteNumByExclusiveRange" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *             &lt;minExclusive value="-129"/>
 *             &lt;maxExclusive value="128"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="shortNumByInclusiveRange" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *             &lt;minInclusive value="-32768"/>
 *             &lt;maxInclusive value="32767"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="shortNumByExclusiveRange">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *             &lt;minExclusive value="-32769"/>
 *             &lt;maxExclusive value="32768"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="intNumByInclusiveRange">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *             &lt;minInclusive value="-2147483648"/>
 *             &lt;maxInclusive value="2147483647"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="intNumByExclusiveRange" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *             &lt;minExclusive value="-2147483649"/>
 *             &lt;maxExclusive value="2147483648"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="longNumByInclusiveRange" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *             &lt;minInclusive value="-9223372036854775808"/>
 *             &lt;maxInclusive value="9223372036854775807"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="longNumByExclusiveRange">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *             &lt;minExclusive value="-9223372036854775809"/>
 *             &lt;maxExclusive value="9223372036854775808"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "from",
    "to",
    "body",
    "anonymousByteElemByDigits",
    "byteElemByDigits"
})
@XmlRootElement(name = "document")
public class Document
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(required = true)
    protected String from;
    @XmlElement(required = true)
    protected String to;
    @XmlElement(required = true)
    protected String body;
    @XmlElement(required = true)
    protected byte anonymousByteElemByDigits;
    protected byte byteElemByDigits;
    @XmlAttribute(name = "floatNum", required = true)
    protected float floatNum;
    @XmlAttribute(name = "doubleNum")
    @Nullable
    protected Double doubleNum;
    @XmlAttribute(name = "decimalNum")
    @Nullable
    protected BigDecimal decimalNum;
    @XmlAttribute(name = "byteNumByDigits")
    @Nullable
    protected Byte byteNumByDigits;
    @XmlAttribute(name = "shortNumByDigits", required = true)
    protected short shortNumByDigits;
    @XmlAttribute(name = "intNumByDigits")
    @Nullable
    protected Integer intNumByDigits;
    @XmlAttribute(name = "longNumByDigits", required = true)
    protected long longNumByDigits;
    @XmlAttribute(name = "bigIntegerNumByDigits")
    @Nullable
    protected BigInteger bigIntegerNumByDigits;
    @XmlAttribute(name = "byteNumByZeroInclusiveRange", required = true)
    protected byte byteNumByZeroInclusiveRange;
    @XmlAttribute(name = "byteNumByZeroExclusiveRange")
    @Nullable
    protected Byte byteNumByZeroExclusiveRange;
    @XmlAttribute(name = "byteNumByInclusiveRange")
    @Nullable
    protected Byte byteNumByInclusiveRange;
    @XmlAttribute(name = "byteNumByExclusiveRange", required = true)
    protected byte byteNumByExclusiveRange;
    @XmlAttribute(name = "shortNumByInclusiveRange", required = true)
    protected short shortNumByInclusiveRange;
    @XmlAttribute(name = "shortNumByExclusiveRange")
    @Nullable
    protected Short shortNumByExclusiveRange;
    @XmlAttribute(name = "intNumByInclusiveRange")
    @Nullable
    protected Integer intNumByInclusiveRange;
    @XmlAttribute(name = "intNumByExclusiveRange", required = true)
    protected int intNumByExclusiveRange;
    @XmlAttribute(name = "longNumByInclusiveRange", required = true)
    protected long longNumByInclusiveRange;
    @XmlAttribute(name = "longNumByExclusiveRange")
    @Nullable
    protected Long longNumByExclusiveRange;

    /**
     * Gets the value of the from property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFrom() {
        return from;
    }

    /**
     * Sets the value of the from property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFrom(String value) {
        this.from = value;
    }

    /**
     * Gets the value of the to property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTo() {
        return to;
    }

    /**
     * Sets the value of the to property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTo(String value) {
        this.to = value;
    }

    /**
     * Gets the value of the body property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBody() {
        return body;
    }

    /**
     * Sets the value of the body property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBody(String value) {
        this.body = value;
    }

    /**
     * Gets the value of the anonymousByteElemByDigits property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public byte getAnonymousByteElemByDigits() {
        return anonymousByteElemByDigits;
    }

    /**
     * Sets the value of the anonymousByteElemByDigits property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAnonymousByteElemByDigits(byte value) {
        this.anonymousByteElemByDigits = value;
    }

    /**
     * Gets the value of the byteElemByDigits property.
     * 
     */
    public byte getByteElemByDigits() {
        return byteElemByDigits;
    }

    /**
     * Sets the value of the byteElemByDigits property.
     * 
     */
    public void setByteElemByDigits(byte value) {
        this.byteElemByDigits = value;
    }

    /**
     * Gets the value of the floatNum property.
     * 
     */
    public float getFloatNum() {
        return floatNum;
    }

    /**
     * Sets the value of the floatNum property.
     * 
     */
    public void setFloatNum(float value) {
        this.floatNum = value;
    }

    /**
     * Gets the value of the doubleNum property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    @Nullable
    public Double getDoubleNum() {
        return doubleNum;
    }

    /**
     * Sets the value of the doubleNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setDoubleNum(
        @Nullable
        Double value) {
        this.doubleNum = value;
    }

    /**
     * Gets the value of the decimalNum property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    @Nullable
    public BigDecimal getDecimalNum() {
        return decimalNum;
    }

    /**
     * Sets the value of the decimalNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDecimalNum(
        @Nullable
        BigDecimal value) {
        this.decimalNum = value;
    }

    /**
     * Gets the value of the byteNumByDigits property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Nullable
    public Byte getByteNumByDigits() {
        return byteNumByDigits;
    }

    /**
     * Sets the value of the byteNumByDigits property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setByteNumByDigits(
        @Nullable
        Byte value) {
        this.byteNumByDigits = value;
    }

    /**
     * Gets the value of the shortNumByDigits property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public short getShortNumByDigits() {
        return shortNumByDigits;
    }

    /**
     * Sets the value of the shortNumByDigits property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setShortNumByDigits(short value) {
        this.shortNumByDigits = value;
    }

    /**
     * Gets the value of the intNumByDigits property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Nullable
    public Integer getIntNumByDigits() {
        return intNumByDigits;
    }

    /**
     * Sets the value of the intNumByDigits property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIntNumByDigits(
        @Nullable
        Integer value) {
        this.intNumByDigits = value;
    }

    /**
     * Gets the value of the longNumByDigits property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public long getLongNumByDigits() {
        return longNumByDigits;
    }

    /**
     * Sets the value of the longNumByDigits property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLongNumByDigits(long value) {
        this.longNumByDigits = value;
    }

    /**
     * Gets the value of the bigIntegerNumByDigits property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Nullable
    public BigInteger getBigIntegerNumByDigits() {
        return bigIntegerNumByDigits;
    }

    /**
     * Sets the value of the bigIntegerNumByDigits property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBigIntegerNumByDigits(
        @Nullable
        BigInteger value) {
        this.bigIntegerNumByDigits = value;
    }

    /**
     * Gets the value of the byteNumByZeroInclusiveRange property.
     * 
     */
    public byte getByteNumByZeroInclusiveRange() {
        return byteNumByZeroInclusiveRange;
    }

    /**
     * Sets the value of the byteNumByZeroInclusiveRange property.
     * 
     */
    public void setByteNumByZeroInclusiveRange(byte value) {
        this.byteNumByZeroInclusiveRange = value;
    }

    /**
     * Gets the value of the byteNumByZeroExclusiveRange property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    @Nullable
    public Byte getByteNumByZeroExclusiveRange() {
        return byteNumByZeroExclusiveRange;
    }

    /**
     * Sets the value of the byteNumByZeroExclusiveRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setByteNumByZeroExclusiveRange(
        @Nullable
        Byte value) {
        this.byteNumByZeroExclusiveRange = value;
    }

    /**
     * Gets the value of the byteNumByInclusiveRange property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    @Nullable
    public Byte getByteNumByInclusiveRange() {
        return byteNumByInclusiveRange;
    }

    /**
     * Sets the value of the byteNumByInclusiveRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setByteNumByInclusiveRange(
        @Nullable
        Byte value) {
        this.byteNumByInclusiveRange = value;
    }

    /**
     * Gets the value of the byteNumByExclusiveRange property.
     * 
     */
    public byte getByteNumByExclusiveRange() {
        return byteNumByExclusiveRange;
    }

    /**
     * Sets the value of the byteNumByExclusiveRange property.
     * 
     */
    public void setByteNumByExclusiveRange(byte value) {
        this.byteNumByExclusiveRange = value;
    }

    /**
     * Gets the value of the shortNumByInclusiveRange property.
     * 
     */
    public short getShortNumByInclusiveRange() {
        return shortNumByInclusiveRange;
    }

    /**
     * Sets the value of the shortNumByInclusiveRange property.
     * 
     */
    public void setShortNumByInclusiveRange(short value) {
        this.shortNumByInclusiveRange = value;
    }

    /**
     * Gets the value of the shortNumByExclusiveRange property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    @Nullable
    public Short getShortNumByExclusiveRange() {
        return shortNumByExclusiveRange;
    }

    /**
     * Sets the value of the shortNumByExclusiveRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setShortNumByExclusiveRange(
        @Nullable
        Short value) {
        this.shortNumByExclusiveRange = value;
    }

    /**
     * Gets the value of the intNumByInclusiveRange property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    @Nullable
    public Integer getIntNumByInclusiveRange() {
        return intNumByInclusiveRange;
    }

    /**
     * Sets the value of the intNumByInclusiveRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setIntNumByInclusiveRange(
        @Nullable
        Integer value) {
        this.intNumByInclusiveRange = value;
    }

    /**
     * Gets the value of the intNumByExclusiveRange property.
     * 
     */
    public int getIntNumByExclusiveRange() {
        return intNumByExclusiveRange;
    }

    /**
     * Sets the value of the intNumByExclusiveRange property.
     * 
     */
    public void setIntNumByExclusiveRange(int value) {
        this.intNumByExclusiveRange = value;
    }

    /**
     * Gets the value of the longNumByInclusiveRange property.
     * 
     */
    public long getLongNumByInclusiveRange() {
        return longNumByInclusiveRange;
    }

    /**
     * Sets the value of the longNumByInclusiveRange property.
     * 
     */
    public void setLongNumByInclusiveRange(long value) {
        this.longNumByInclusiveRange = value;
    }

    /**
     * Gets the value of the longNumByExclusiveRange property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    @Nullable
    public Long getLongNumByExclusiveRange() {
        return longNumByExclusiveRange;
    }

    /**
     * Sets the value of the longNumByExclusiveRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setLongNumByExclusiveRange(
        @Nullable
        Long value) {
        this.longNumByExclusiveRange = value;
    }

}
