//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.13 at 06:28:53 PM YEKT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "com.github.tr1cks.xjcplugins", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.github.tr1cks.xjcplugins;
